services:
  - type: web
    name: qr-attendance-api
    env: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: qr-attendance-db
          property: connectionString

databases:
  - name: qr-attendance-db
    plan: free
    region: oregon
