// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AhUwkfkiR1ta6TLPd7hjTrDZlPu_1qI',
    appId: '1:380742054455:web:c4d3fc3ae3cab6890605b2',
    messagingSenderId: '380742054455',
    projectId: 'attendance-monitoring-sy-89218',
    authDomain: 'attendance-monitoring-sy-89218.firebaseapp.com',
    storageBucket: 'attendance-monitoring-sy-89218.firebasestorage.app',
    measurementId: 'G-59C4W6MHN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAha5TvnJVkCBvj9illFXoKFM_Ub5hUmWI',
    appId: '1:380742054455:android:2993b0688bf936940605b2',
    messagingSenderId: '380742054455',
    projectId: 'attendance-monitoring-sy-89218',
    storageBucket: 'attendance-monitoring-sy-89218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHEE9QSBED6kB80eVweCQ9Lhb3IDN4fIM',
    appId: '1:380742054455:ios:9546e41d66aea7cb0605b2',
    messagingSenderId: '380742054455',
    projectId: 'attendance-monitoring-sy-89218',
    storageBucket: 'attendance-monitoring-sy-89218.firebasestorage.app',
    iosBundleId: 'com.example.attendancePortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHEE9QSBED6kB80eVweCQ9Lhb3IDN4fIM',
    appId: '1:380742054455:ios:9546e41d66aea7cb0605b2',
    messagingSenderId: '380742054455',
    projectId: 'attendance-monitoring-sy-89218',
    storageBucket: 'attendance-monitoring-sy-89218.firebasestorage.app',
    iosBundleId: 'com.example.attendancePortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4AhUwkfkiR1ta6TLPd7hjTrDZlPu_1qI',
    appId: '1:380742054455:web:000eff1d048a8b350605b2',
    messagingSenderId: '380742054455',
    projectId: 'attendance-monitoring-sy-89218',
    authDomain: 'attendance-monitoring-sy-89218.firebaseapp.com',
    storageBucket: 'attendance-monitoring-sy-89218.firebasestorage.app',
    measurementId: 'G-389E7Z8JB5',
  );
}
